all: Esercizio 	
	./Esercizio_1.3

Esercizio: Esercizio.o funzioni.o
	g++ Esercizio_1.3.o funzioni.o -o Esercizio_1.3 

Esercizio.o: Esercizio_1.3.cc funzioni.hh
	g++ -c Esercizio_1.3.cc -o Esercizio_1.3.o

funzioni.o: funzioni.cc funzioni.hh
	g++ -c funzioni.cc -o funzioni.o


	


 
