esercizio2.1: scambiacontatore.o funzioni.o
	g++ scambiacontatore.o funzioni.o -o esercizio2.1
scambiacontatore.o: scambiacontatore.cpp
	g++ -c scambiacontatore.cpp -o scambiacontatore.o
funzioni.o: funzioni.cpp funzioni.hpp
	g++ -c funzioni.cpp -o funzioni.o
