all: esercizio1.3
esercizio1.3: esercizio1.3.o funzioni.o
	g++ esercizio1.3.o -o esercizio1.3
esercizio1.3.o: esercizio1.3.cc 
	g++ -c esercizio1.3.cc -o esercizio1.3.o
funzioni.o: funzioni.cc
	g++ -c funzioni.cc -o funzioni.o
