esercizio7.1: main.o trigonometric.o integrale.o
	g++ main.o trigonometric.o integrale.o -o esercizio7.1 
main.o: main.cpp
	g++ -c main.cpp -o main.o 
trigonometric.o: trigonometric.cpp funzionebase.h
	g++ -c trigonometric.cpp -o trigonometric.o
integrale.o: integrale.cpp
	g++ -c integrale.cpp -o integrale.o
