all:Esercizio

Esercizio: Esercizio.o funzioni.o
	g++ Esercizio.o funzioni.o -o Esercizio_1.2

Esercizio.o: Esercizio_1.2.cc funzioni.hh
	g++ -c Esercizio_1.2.cc -o Esercizio.o

funzioni.o: funzioni.cc funzioni.hh
	g++ -c funzioni.cc -o funzioni.o




