esercizio3.3: corpoceleste.o elettrone.o particella.o posizione.o main.o
	g++ corpoceleste.o elettrone.o particella.o posizione.o main.o -o esercizio3.3
corpoceleste.o: corpoceleste.cpp corpoceleste.hpp
	g++ -c corpoceleste.cpp -o corpoceleste.o
elettrone.o: elettrone.cpp elettrone.hpp
	g++ -c elettrone.cpp -o elettrone.o
particella.o: particella.cpp particella.hpp
	g++ -c particella.cpp -o particella.o
posizione.o: posizione.cpp posizione.hpp
	g++ -c posizione.cpp -o posizione.o
main.o: main.cpp
	g++ -c main.cpp -o main.o
