esercizio5.2: bisezione.o parabola.o main.o
	g++ bisezione.o parabola.o main.o -o esercizio5.2
bisezione.o: bisezione.cpp bisezione.hpp
	g++ -g -c bisezione.cpp -o bisezione.o
parabola.o: parabola.cpp parabola.h
	g++ -g -c parabola.cpp -o parabola.o
main.o: main.cpp
	g++ -g -c main.cpp -o main.o
