esercizio1.2: paridispari.o funzioni.o
	g++ paridispari.o funzioni.o -o esercizio1.2
paridispari.o: paridispari.cpp
	g++ -c paridispari.cpp -o paridispari.o
funzioni.o: funzioni.cpp
	g++ -c funzioni.cpp -o funzioni.o
