esercizio1.4: modulo.o funzioni.o
	g++ modulo.o funzioni.o -o esercizio1.4
modulo.o: modulo.cpp
	g++ -c modulo.cpp -o modulo.o
funzioni.o: funzioni.cpp funzioni.hpp
	g++ -c funzioni.cpp -o funzioni.o
