esercizio1.3: calcoli.o funzioni.o
	g++ calcoli.o funzioni.o -o esercizio1.3
calcoli.o: calcoli.cpp
	g++ -c calcoli.cpp -o calcoli.o
funzioni.o: funzioni.cpp funzioni.hpp
	g++ -c funzioni.cpp -o funzioni.o
