esercizio3.1: esercizio.o posizione.o
	g++ esercizio.o posizione.o -o esercizio3.1
esercizio.o: esercizio.cpp
	g++ -c esercizio.cpp -o esercizio.o
posizione.o: posizione.cpp posizione.hpp
	g++ -c posizione.cpp -o posizione.o
