esercizio5.3: bisezione.o main.o particulartrigonometric.o
	g++ bisezione.o main.o particulartrigonometric.o -o esercizio5.3
bisezione.o: bisezione.cpp bisezione.hpp
	g++ -c bisezione.cpp -o bisezione.o
particulartrigonometric.o: particulartrigonometric.cpp particulartrigonometric.h
	g++ -c particulartrigonometric.cpp -o particulartrigonometric.o
main.o: main.cpp
	g++ -c main.cpp -o main.o
