esercizio2.2: selectionsort.o funzioni.o
	g++ selectionsort.o funzioni.o -o esercizio2.2
selectionsort.o: selectionsort.cpp
	g++ -c selectionsort.cpp -o selectionsort.o
funzioni.o: funzioni.cpp funzioni.hpp
	g++ -c funzioni.cpp -o funzioni.o
